server:
  port: 7001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: file_route
          uri: lb://file-service
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            - StripPrefix=1

        - id: admin_route
          uri: lb://admin-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848