server:
  port: 7001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors: # 全局跨域配置
        add-to-simple-url-handler-mapping: true # 解决Options请求别拦截问题
          # options请求 就是一种询问服务器是否浏览器可以跨域的请求
          # 如果每次跨域都有询问服务器是否浏览器可以跨域, 这对性能也是损耗
          # 可以配置本次跨域检测的有效期maxAge, 在maxAge时间范围内, 统统允许跨域
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
            maxAge: 360000


      routes:
        - id: file_route
          uri: lb://file-service
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            - StripPrefix=1

        - id: member_route
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            - StripPrefix=1

        - id: coupon_route
          uri: lb://conpon-service
          predicates:
            - Path=/api/conpon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            - StripPrefix=1

        - id: admin_route
          uri: lb://admin-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848